import { assets } from "../assets/figma";
import { LATEST_MODEL_DATE } from "./modelOptions";
import type { Plan, Tactic } from "./types";

export const PLANS: Plan[] = [
  {
    id: "default",
    label: "Default Plan",
    kind: "optimization",
    createdBy: "AS",
    lastEdited: new Date(2026, 7, 1),
    target: "incremental-roas",
    planStart: new Date(2026, 6, 2),
    planEnd: new Date(2026, 7, 1),
    shared: true,
  },
  {
    id: "sim-default",
    label: "Q3 2026 media simulation",
    kind: "simulation",
    createdBy: "JH",
    lastEdited: new Date(2026, 7, 10),
    target: "incremental-sales",
    targetValue: 9_500_000,
    planStart: new Date(2026, 6, 12),
    planEnd: new Date(2026, 7, 10),
    shared: true,
  },
  {
    id: "sim-q3-inflight",
    label: "Q3 2026 quarterly simulation",
    kind: "simulation",
    createdBy: "JH",
    lastEdited: new Date(2026, 7, 20),
    target: "incremental-sales",
    targetValue: 24_000_000,
    planStart: new Date(2026, 6, 1),
    planEnd: new Date(2026, 8, 30),
    shared: false,
    modelDate: LATEST_MODEL_DATE,
  },
  {
    id: "sim-default-copy",
    label: "Q3 2026 media simulation (copy)",
    kind: "simulation",
    createdBy: "JH",
    lastEdited: new Date(2026, 7, 10),
    target: "incremental-roas",
    targetValue: 12,
    planStart: new Date(2026, 6, 12),
    planEnd: new Date(2026, 7, 10),
    editVariant: "sidebar",
  },
];

export const INITIAL_TACTICS: Tactic[] = [
  {
    id: "gpm",
    name: "Google Performance Max",
    channel: "Search",
    logo: assets.google,
    budgetOld: 243_988,
    budgetNew: 318_638,
    locked: false,
    salesOld: 1_100_000,
    marginalRoas: 5.21,
  },
  {
    id: "fb",
    name: "Facebook Prospecting",
    channel: "Social",
    logo: assets.meta,
    budgetOld: 111_245,
    budgetNew: 124_995,
    locked: false,
    salesOld: 850_000,
    marginalRoas: 4.8,
  },
  {
    id: "tiktok",
    name: "TikTok Prospecting",
    channel: "Social",
    logo: assets.tiktok,
    budgetOld: 98_500,
    budgetNew: 98_500,
    locked: true,
    salesOld: 450_000,
    marginalRoas: 3.1,
  },
  {
    id: "bing",
    name: "Bing Non-Brand Search",
    channel: "Search",
    logo: assets.bing,
    budgetOld: 51_096,
    budgetNew: 45_200,
    locked: false,
    salesOld: 5_400_000,
    marginalRoas: 1.95,
  },
  {
    id: "snap",
    name: "Snapchat Search",
    channel: "Social",
    logo: assets.snapchat,
    budgetOld: 32_000,
    budgetNew: 32_000,
    locked: true,
    salesOld: 120_000,
    marginalRoas: 2.0,
  },
];

export const DEFAULT_TARGET_BUDGET = 1_500_000;
